# Default pipeline to build, check and test libhtp-rs
#
# This will also run integration tests with cyberdeck and suricata.

trigger:
  batch: true
  branches:
    include:
      - main

pr:
- main

resources:
  repositories:
  - repository: suricata
    type: github
    name: CybercentreCanada/suricata-internal
    endpoint: CybercentreCanada
    ref: refs/heads/libhtp-rs
  - repository: cyberdeck
    type: github
    name: CybercentreCanada/cyberdeck
    endpoint: CybercentreCanada
    ref: refs/heads/libhtp-rs-fixes
  - repository: suricata-verify
    type: github
    name: CybercentreCanada/suricata-verify-internal
    endpoint: CybercentreCanada
    ref: refs/heads/libhtp-rs

stages:
- stage: test
  pool: nbs-gcc-9-autoscaling-builders
  dependsOn: []
  jobs:
  - job: test
    timeoutInMinutes: 180
    displayName: Test LibHTP
    steps:
      - template: qa-steps.yml

- stage: fuzz
  pool: nbs-gcc-9-autoscaling-builders
  dependsOn: []
  jobs:
  - job: fuzz
    displayName: Fuzz LibHTP
    steps:
      - template: fuzz-steps.yml
