# Default pipeline to build, check and test libhtp2
#
# This will also run integration tests with cyberdeck and suricata.

trigger:
  batch: true
  branches:
    include:
      - main

pr:
- main

resources:
  repositories:
  - repository: suricata
    type: github
    name: CybercentreCanada/suricata-internal
    endpoint: CybercentreCanada
    ref: refs/heads/libhtp-rs
  - repository: cyberdeck
    type: github
    name: CybercentreCanada/cyberdeck
    endpoint: CybercentreCanada
    ref: refs/heads/libhtp-rs-fixes
  - repository: suricata-verify
    type: github
    name: CybercentreCanada/suricata-verify-internal
    endpoint: CybercentreCanada
    ref: refs/heads/libhtp-rs

jobs:
- job: test_libhtp2
  timeoutInMinutes: 180
  displayName: Test Libhtp2
  pool: nbs-gcc-9-autoscaling-builders
  steps:
    #
    # Libhtp2 Steps
    # ==============
    - checkout: self
      path: libhtp2

    # Use cargo install path
    - script: echo "##vso[task.setvariable variable=PATH;]$PATH:/usr/local/cargo/bin"
      displayName: set path

    # Give builder access to cached rust install
    - script: sudo chown -R AzDevOps /usr/local/cargo /usr/local/rustup
      displayName: chown cargo dir

    #
    # Setup dependencies required to build libhtp2
    - script: |
        rustup override set stable
      displayName: setup
      workingDirectory: $(Agent.BuildDirectory)/libhtp2
    
    #
    # Check code formatting differences
    - script: cargo fmt -- --check
      displayName: rustfmt
      workingDirectory: $(Agent.BuildDirectory)/libhtp2
    
    #
    # Check linting warnings
    - script: cargo clippy --all-targets -- -D warnings
      displayName: Run Clippy
      workingDirectory: $(Agent.BuildDirectory)/libhtp2
    
    #
    # Build the rust targets
    - script: make
      displayName: build
      workingDirectory: $(Agent.BuildDirectory)/libhtp2
    
    #
    # Run the unit tests
    - script: |
        rustup override set nightly
        rustup component add llvm-tools-preview
        RUSTFLAGS="-C instrument-coverage" LLVM_PROFILE_FILE="coverage-%p-%m.profraw" cargo test --workspace
      displayName: test
      workingDirectory: $(Agent.BuildDirectory)/libhtp2

    #
    # Generate the code coverage
    - script: |
        grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "*cargo*" -o ./coverage.lcov
        lcov_cobertura ./coverage.lcov --output ./coverage.xml
      displayName: code coverage
      workingDirectory: $(Agent.BuildDirectory)/libhtp2
      continueOnError: True

    #
    # Use .Net Core SDK for code coverage report generation
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk'
      inputs:
        packageType: sdk
        version: 3.1.402
        installationPath: $(Agent.ToolsDirectory)/dotnet

    #
    # Generate the code coverage report for Azure
    - script: |
         dotnet tool install -g dotnet-reportgenerator-globaltool
         reportgenerator -reports:./coverage.xml -targetdir:./coverage/ "-reporttypes:HtmlInline_AzurePipelines;Cobertura"
      displayName: generate code coverage report
      workingDirectory: $(Agent.BuildDirectory)/libhtp2
      continueOnError: True

    #
    # Publish the Azure code coverage results
    - task: PublishCodeCoverageResults@1
      displayName: publish code coverage
      continueOnError: True
      inputs:
       codeCoverageTool: Cobertura
       summaryFileLocation: '$(Agent.BuildDirectory)/libhtp2/coverage.xml'
       reportDirectory: '$(Agent.BuildDirectory)/libhtp2/coverage/'

    #
    # Run the benchmarks
    - script: |
        rustup override set stable
        cargo bench
      displayName: bench
      workingDirectory: $(Agent.BuildDirectory)/libhtp2

    #
    # Build rpm
    - script: make rpm
      displayName: rpm
      workingDirectory: $(Agent.BuildDirectory)/libhtp2
    
    #
    # Install libhtp2
    #
    # TODO: Link to cyberdeck without installing RPM to avoid polluting the global environment
    - script: |
        sudo yum remove -y libhtp
        sudo yum install -y target/centos/RPMS/x86_64/libhtp*.rpm
      displayName: install
      workingDirectory: $(Agent.BuildDirectory)/libhtp2

    #
    # Suricata Steps
    # ==============
    
    #
    # Checkout Suricata
    - checkout: suricata
      path: suricata

    #
    # Configure suricata
    #
    # The symlink should prevent us from having to rebuild libhtp2.
    - script: |
        ln -s $(Agent.BuildDirectory)/libhtp2 libhtp
        ./autogen.sh
        $(Agent.BuildDirectory)/suricata/configure --enable-unittests
      displayName: "suricata: configure"
      workingDirectory: $(Agent.BuildDirectory)/suricata
    
    #
    # Build suricata
    - script: |
        make -j $(nproc)
      displayName: "suricata: build"
      workingDirectory: $(Agent.BuildDirectory)/suricata
    
    #
    # Test suricata
    - script: |
        mkdir -p /var/log/suricata
        rm -f /var/log/suricata/boo.txt
        ./src/suricata -u
      displayName: "suricata: test"
      workingDirectory: $(Agent.BuildDirectory)/suricata

    #
    # Suricata-Verify Steps
    # ==============
    
    #
    # Checkout suricata-verify
    - checkout: suricata-verify
      path: suricata-verify

    #
    # Test suricata-verify
    - script: |
        python3 $(Agent.BuildDirectory)/suricata-verify/run.py
      displayName: "suricata-verify: test"
      workingDirectory: $(Agent.BuildDirectory)/suricata

    #
    # Cyberdeck Steps
    # ==============

    #
    # Checkout cyberdeck
    - checkout: cyberdeck
      path: cyberdeck

    #
    # Configure cyberdeck
    #
    # This will configure cyberdeck outside of its source tree.
    #
    # TODO: link to libhtp2
    - script: |
        mkdir cyberdeck_build
        cd cyberdeck_build
        source /opt/gcc-9/enable
        cmake3 -DTARGET_NATIVE_ARCH=Off -DCMAKE_BUILD_TYPE=Release -DENABLE_SAWP=Off -DENABLE_MANPAGES=Off -DENABLE_STREAMMAP=Off -DENABLE_SNF=Off $(Agent.BuildDirectory)/cyberdeck
      displayName: "cyberdeck: configure" 
      workingDirectory: $(Agent.BuildDirectory)
    
    #
    # Build cyberdeck
    - script: |
        make -j $(nproc)
      displayName: "cyberdeck: build" 
      workingDirectory: $(Agent.BuildDirectory)/cyberdeck_build

    #
    # Test cyberdeck
    - script: ice/HTTP/test/http_unit_tests
      displayName: "cyberdeck: test http"
      workingDirectory: $(Agent.BuildDirectory)/cyberdeck_build
