# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr:
- master

resources:
  repositories:
  - repository: cyberdeck
    type: bitbucket
    endpoint: rtmorti
    name: cse-nbs/cyberdeck
    ref: refs/heads/libhtp-rs-fixes

jobs:
- job: install_rust
  displayName: Install Rust
  pool: libhtp-builders
  steps:
    - script: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
        echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
      displayName: Install Rust

- job: install_lib
  displayName: Build and Install libhtp-rs
  dependsOn: install_rust
  pool: libhtp-builders
  steps:
    - checkout: self
    - script: echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    - script: . /opt/gcc-9/enable
    - script: make rpm
      displayName: Build
    - script: |
        sudo yum remove -y libhtp
        sudo yum install -y target/centos/RPMS/x86_64/libhtp*.rpm
      displayName: Install

- job: build_cyberdeck
  displayName: Building Cyberdeck
  dependsOn: install_lib
  pool: libhtp-builders
  steps:
    - checkout: cyberdeck
    - script: |
        mkdir build
        cd build
        source /opt/gcc-9/enable
        cmake3 -DTARGET_NATIVE_ARCH=Off -DCMAKE_BUILD_TYPE=Release -DENABLE_MANPAGES=Off -DENABLE_STREAMMAP=Off -DENABLE_SNF=Off ..
        make -j4
      displayName: Build Cyberdeck
    - script: build/ice/HTTP/test/http_unit_tests
      displayName: Run HTTP tests