# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr:
- master

resources:
  repositories:
  - repository: suricata
    type: bitbucket
    endpoint: rtmorti
    name: cse-nbs/suricata
    ref: 'refs/heads/libhtp-rs'

jobs:
- job: install_rust
  displayName: Install Rust
  pool: libhtp-builders
  steps:
    - script: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
        echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
        cargo install --force --version 0.14.1 cbindgen
      displayName: Install Rust

- job: build_suricata
  displayName: Build and Test Suricata with libhtp-rs
  dependsOn: install_rust
  pool: libhtp-builders
  steps:
    - checkout: suricata
      path: suricata
    - checkout: self
      path: suricata/libhtp
    - script: echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
      displayName: Set Cargo Path
    - script: |
        ./autogen.sh
        ./configure --enable-unittests
        make
      displayName: Build Suricata
      workingDirectory: $(Agent.BuildDirectory)/suricata
    - script: |
        mkdir -p /var/log/suricata
        rm -f /var/log/suricata/boo.txt
      displayName: Set Up Test Environment
    - script: ./src/suricata -u
      displayName: Run Suricata Tests
      workingDirectory: $(Agent.BuildDirectory)/suricata
