[workspace]
members = [
]

[package]
name = "libhtp2"
authors = ["C2Rust"]
version = "0.0.0"
publish = false
edition = "2018"
autobins = false
license-file = "LICENSE"

[lib]
name = "libhtp2"
path = "lib.rs"
crate-type = ["staticlib", "rlib", "cdylib"]


[dependencies]
libc = "0.2"
bitflags = "1.2.1"


